version: "3.8"
services:
  database:
    image: 'mysql'
    ports:
      - '3306:3306'
    env_file: ".env"
    volumes:
      - './data/db/:/var/lib/mysql'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8082:80'
    container_name: phpmyadmin
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
    depends_on:
      - database
