spring.application.name=prod

# Désactive la connexion a la
# spring.datasource.enabled=false
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Connexion a la BDD (perso)
spring.datasource.url=jdbc:mysql://localhost:3306/db_re_sources_relationnelles
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Defini les chemins des vues
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.jpa.hibernate.ddl-auto=update