name: backend-ci-cd-dryrun

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend-build-test:
    name: Backend — build & tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: m2-${{ runner.os }}-${{ hashFiles('backend/pom.xml') }}
          restore-keys: |
            m2-${{ runner.os }}-

      - name: Maven verify (tests inclus)
        run: mvn -B -DskipTests=false -f backend/pom.xml verify

      - name: Récup artefact JAR
        run: |
          mkdir -p out
          if ls backend/target/*.jar >/dev/null 2>&1; then
            cp $(ls -t backend/target/*.jar | head -n1) out/app-backend.jar
          else
            echo "(Jar d’exemple)" > out/app-backend.jar
          fi

      - name: Sécu — dry run
        run: echo "[DRY-RUN] OWASP Dependency-Check / CodeQL" | tee out/security-backend.txt

      - name: Docker build — dry run
        env:
          SHA: ${{ github.sha }}
        run: echo "[DRY-RUN] docker build -t example.local/re-sources-backend:${SHA} backend" | tee -a out/docker.txt

      - name: Deploy — dry run
        run: echo "[DRY-RUN] ssh prod && docker compose up -d" | tee -a out/deploy.txt

      - uses: actions/upload-artifact@v4
        with:
          name: backend-dryrun-artifacts
          path: out/*
