name: frontend-ci-cd-dryrun

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Frontend — build (dry run)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps
        working-directory: frontend
        run: |
          if [ -f package.json ]; then
            if [ -f package-lock.json ]; then
              npm ci
            else
              npm install
            fi
          else
            echo "Aucun package.json dans frontend/ — skip install"
          fi

      - name: Build
        working-directory: frontend
        run: |
          if [ -f package.json ]; then
            if npm run | grep -q " build"; then
              npm run build
            else
              echo "Aucun script 'build' — génération d'un dist de démonstration"
              mkdir -p dist && echo "dist demo" > dist/index.html
            fi
          else
            echo "Aucun package.json — génération d'un dist de démonstration"
            mkdir -p dist && echo "dist demo" > dist/index.html
          fi

      - name: Pack artefacts
        run: |
          mkdir -p out
          if [ -d frontend/dist ]; then
            tar -czf out/frontend-dist.tgz -C frontend/dist .
          else
            echo "(dist d’exemple)" > out/frontend-dist.txt
          fi

      - name: Sécu — dry run
        run: echo "[DRY-RUN] npm audit / ESLint" | tee out/security-frontend.txt

      - name: Docker build — dry run
        env:
          SHA: ${{ github.sha }}
        run: echo "[DRY-RUN] docker build -t example.local/re-sources-frontend:${SHA} frontend" | tee -a out/docker.txt

      - uses: actions/upload-artifact@v4
        with:
          name: frontend-dryrun-artifacts
          path: out/*
